### ISSUE TITLE
[HELP WANTED]: Error with Jobs Description

### ISSUE THREAD

**Issue by ChristOscar** [feder-cr/Auto_Jobs_Applier_AIHawk#438]
## Issue Description

Our LinkedIn job application bot is encountering an error when trying to retrieve the job description. The error occurs in the `_get_job_description` method of the `AIHawkEasyApplier` class. The bot is unable to locate the element containing the job description.

## Error Message

```
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".jobs-description-content__text"}
  (Session info: chrome=129.0.6668.59)
```

## Code Snippet

Here's the relevant part of the `_get_job_description` method where the error occurs:

```python
def _get_job_description(self) -> str:
    logger.debug("Getting job description")
    try:
        try:
            see_more_button = self.driver.find_element(By.XPATH,
                                                       '//button[@aria-label="Click to see more description"]')
            actions = ActionChains(self.driver)
            actions.move_to_element(see_more_button).click().perform()
            time.sleep(2)
        except NoSuchElementException:
            logger.debug("See more button not found, skipping")

        description = self.driver.find_element(By.CLASS_NAME, 'jobs-description-content__text').text
        logger.debug("Job description retrieved successfully")
        return description
    except NoSuchElementException:
        tb_str = traceback.format_exc()
        logger.error(f"Job description not found: {tb_str}")
        raise Exception(f"Job description not found: \nTraceback:\n{tb_str}")
    except Exception:
        tb_str = traceback.format_exc()
        logger.error(f"Error getting Job description: {tb_str}")
        raise Exception(f"Error getting Job description: \nTraceback:\n{tb_str}")
```

## Steps to Reproduce

1. Run the LinkedIn job application bot
2. Bot navigates to a job listing page
3. Bot attempts to retrieve the job description
4. Error occurs when trying to find the element with class name 'jobs-description-content__text'

## Expected Behavior

The bot should successfully locate and retrieve the job description text from the LinkedIn job listing page.

## Actual Behavior

The bot fails to locate the element containing the job description, raising a `NoSuchElementException`.

## Questions

1. Has LinkedIn changed their HTML structure for job listings recently?
2. Are there alternative selectors we could use to locate the job description?
3. Could this be related to page load timing issues?
4. Are there any known issues with Selenium and the current versions of Chrome/ChromeDriver we're using?

Thank you in advance for your help!

**Comment by craschnet** [comment]
Having the same issue.

**Comment by craschnet** [comment]
> ### Issue description
> ## Issue Description
> 
> Our LinkedIn job application bot is encountering an error when trying to retrieve the job description. The error occurs in the `_get_job_description` method of the `AIHawkEasyApplier` class. The bot is unable to locate the element containing the job description.
> ## Error Message
> 
> ```
> selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".jobs-description-content__text"}
>   (Session info: chrome=129.0.6668.59)
> ```
> 
> ## Code Snippet
> 
> Here's the relevant part of the `_get_job_description` method where the error occurs:
> 
> ```python
> def _get_job_description(self) -> str:
>     logger.debug("Getting job description")
>     try:
>         try:
>             see_more_button = self.driver.find_element(By.XPATH,
>                                                        '//button[@aria-label="Click to see more description"]')
>             actions = ActionChains(self.driver)
>             actions.move_to_element(see_more_button).click().perform()
>             time.sleep(2)
>         except NoSuchElementException:
>             logger.debug("See more button not found, skipping")
> 
>         description = self.driver.find_element(By.CLASS_NAME, 'jobs-description-content__text').text
>         logger.debug("Job description retrieved successfully")
>         return description
>     except NoSuchElementException:
>         tb_str = traceback.format_exc()
>         logger.error(f"Job description not found: {tb_str}")
>         raise Exception(f"Job description not found: \nTraceback:\n{tb_str}")
>     except Exception:
>         tb_str = traceback.format_exc()
>         logger.error(f"Error getting Job description: {tb_str}")
>         raise Exception(f"Error getting Job description: \nTraceback:\n{tb_str}")
> ```
> 
> ## Steps to Reproduce
> 
>     1. Run the LinkedIn job application bot
> 
>     2. Bot navigates to a job listing page
> 
>     3. Bot attempts to retrieve the job description
> 
>     4. Error occurs when trying to find the element with class name 'jobs-description-content__text'
> 
> 
> ## Expected Behavior
> 
> The bot should successfully locate and retrieve the job description text from the LinkedIn job listing page.
> ## Actual Behavior
> 
> The bot fails to locate the element containing the job description, raising a `NoSuchElementException`.
> ## Questions
> 
>     1. Has LinkedIn changed their HTML structure for job listings recently?
> 
>     2. Are there alternative selectors we could use to locate the job description?
> 
>     3. Could this be related to page load timing issues?
> 
>     4. Are there any known issues with Selenium and the current versions of Chrome/ChromeDriver we're using?
> 
> 
> Thank you in advance for your help!
> ### Specific tasks
> 
> _No response_
> ### Additional resources
> 
> _No response_
> ### Additional context
> 
> _No response_

I have LinkedIn Premium.
Do you have LinkedIn premium?

**Comment by craschnet** [comment]
@ [ChristOscar](https://github.com/ChristOscar)
Looks like it's being updated. See:

https://github.com/feder-cr/Auto_Jobs_Applier_AIHawk/pull/449

**Comment by craschnet** [comment]
```
2024-09-30 19:35:22.488 | DEBUG    | src.aihawk_easy_applier:_find_easy_apply_button:188 - Found 'Easy Apply' button 2, attempting to click
2024-09-30 19:35:22.494 | DEBUG    | src.aihawk_easy_applier:job_apply:118 - Retrieving job description
2024-09-30 19:35:22.494 | DEBUG    | src.aihawk_easy_applier:_get_job_description:223 - Getting job description
2024-09-30 19:35:22.515 | DEBUG    | src.aihawk_easy_applier:_get_job_description:232 - See more button not found, skipping
2024-09-30 19:35:22.540 | ERROR    | src.aihawk_easy_applier:_get_job_description:239 - Job description not found: Traceback (most recent call last):
  File "/home/crasch/Auto_Jobs_Applier_AIHawk/src/aihawk_easy_applier.py", line 234, in _get_job_description
    description = self.driver.find_element(By.CLASS_NAME, 'jobs-description-content__text').text
  File "/home/crasch/Auto_Jobs_Applier_AIHawk/virtual/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 831, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "/home/crasch/Auto_Jobs_Applier_AIHawk/virtual/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/home/crasch/Auto_Jobs_Applier_AIHawk/virtual/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".jobs-description-content__text"}
  (Session info: chrome=129.0.6668.70)
Stacktrace:
#0 0x569d6a93810a <unknown>
#1 0x569d6a61e5e0 <unknown>
#2 0x569d6a66dbe8 <unknown>
#3 0x569d6a66de81 <unknown>
#4 0x569d6a6b48c4 <unknown>
#5 0x569d6a692b4d <unknown>
#6 0x569d6a6b1d7d <unknown>
#7 0x569d6a6928c3 <unknown>
#8 0x569d6a6606b3 <unknown>
#9 0x569d6a66168e <unknown>
#10 0x569d6a902b0b <unknown>
#11 0x569d6a906a91 <unknown>
#12 0x569d6a8ef305 <unknown>
#13 0x569d6a907612 <unknown>
#14 0x569d6a8d446f <unknown>
#15 0x569d6a927008 <unknown>
#16 0x569d6a9271d3 <unknown>
#17 0x569d6a936f5c <unknown>
#18 0x7133a7694ac3 <unknown>
```

It looks like it's trying to click the second "Easy Apply" Button that shows up when it scrolls down.

**Comment by craschnet** [comment]
Hi https://github.com/ChristOscar
I'm troubleshooting this issue in: https://github.com/feder-cr/Auto_Jobs_Applier_AIHawk/issues/457
Seems to be an issue with using Linkedin Premium. 
It changes the name of the elements. I canceled my linkedin premium subscription (and it won't change back till 10/17/2024) so it maybe two weeks before I can use it again. 
I'm just started to learn python due to looking into this issue.

**Comment by queukat** [comment]
fixed in https://github.com/feder-cr/Auto_Jobs_Applier_AIHawk/pull/473

**Comment by xTaylorFerg** [comment]
The issue with finding the description when user is LinkedIn Premium is not fixed in this commit. It is not fixed in main or the v4 branch. Someone opened an issue for it here:
https://github.com/feder-cr/Auto_Jobs_Applier_AIHawk/issues/457
